FROM alpine

RUN apk add --no-cache \
        python3

RUN mkdir /domains/
RUN mkdir /app/

COPY ./server ./app

WORKDIR /app

RUN pip3 install --no-cache-dir -r requirements.txt

CMD [ "python3", "app.py" ]
