version: '3'

services:

  nginx-static:
    build:
      context: ./
      dockerfile: Dockerfile-nginx-static
    volumes:
      - ./domains:/domains:ro

  flask:
    build:
      context: ./
      dockerfile: Dockerfile-flask
    volumes:
      - ./domains:/domains
    ports:
      - 9099:80
