version: '3'

services:

  flask:
    build:
      context: ./
      dockerfile: Dockerfile-flask
    volumes:
      - ./domains:/domains
    ports:
      - "5050:5050"

  nginx-static:
    build:
      context: ./
      dockerfile: Dockerfile-nginx-static
    volumes:
      - ./domains:/domains
    ports:
      - "5051:80"
