FROM alpine

RUN apk add --no-cache \
        uwsgi-python3 \
        python3

RUN mkdir /domains/
RUN mkdir /app/

COPY ./server ./app

WORKDIR /app

RUN pip3 install --no-cache-dir -r requirements.txt

EXPOSE 5050

CMD [ "uwsgi", "--socket", "0.0.0.0:5050", \
               "--uid", "root", \
               "--plugins", "python3", \
               "--protocol", "uwsgi", \
               "--wsgi", "app:app" ]
